const PDFDocument = require('pdfkit');

function generateValuationPDF(valuation, res) {
  const doc = new PDFDocument({ margin: 50 });

  res.setHeader('Content-Type', 'application/pdf');
  res.setHeader('Content-Disposition', `attachment; filename=valuation-report-${valuation.id}.pdf`);

  doc.pipe(res);

  const formatCurrency = (val) => {
    const num = Math.round(Number(val));
    return `Rs. ${num.toLocaleString('en-IN')}`;
  };

  const factors = valuation.valuationFactors || {};
  const pricePerSqFt = factors.benchmarkPricePerSqFt || 
    (valuation.property?.squareFeet ? valuation.estimatedValue / valuation.property.squareFeet : null);

  // Header
  doc.fillColor('#1A202C').fontSize(22).text('PropTech Property Intelligence', { align: 'center' });
  doc.fontSize(12).fillColor('#718096').text('Automated Property Appraisal Report', { align: 'center' });
  doc.moveDown(2);

  // Summary
  doc.fillColor('#2D3748').fontSize(14).text(`Report ID: ${valuation.id}`);
  doc.fontSize(10).text(`Generated Date: ${new Date(valuation.createdAt || Date.now()).toLocaleDateString('en-IN')}`);
  doc.moveDown();

  doc.fontSize(16).fillColor('#2B6CB0').text(`Estimated Valuation: ${formatCurrency(valuation.estimatedValue)}`);
  doc.moveDown();

  doc.fontSize(11).fillColor('#2D3748');
  doc.text(`Property ID: ${valuation.propertyId}`);
  if (pricePerSqFt) {
    doc.text(`Calculated Price / SqFt: ${formatCurrency(pricePerSqFt)}`);
  }
  doc.moveDown(2);

  // Footer
  doc.fontSize(9).fillColor('#A0AEC0').text('This automated appraisal is generated by the PropTech market trend engine for analytical purposes.', { align: 'center' });

  doc.end();
}

module.exports = { generateValuationPDF };
